---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: malcolm
spec:
  ports:
    - port: 9200
      protocol: TCP
      name: opensearch
  selector:
    name: opensearch-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: opensearch-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: opensearch-deployment
    spec:
      containers:
      - name: opensearch-container
        image: ghcr.io/idaholab/malcolm/opensearch:23.09.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        ports:
          - name: opensearch
            protocol: TCP
            containerPort: 9200
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: opensearch-env
        env:
          - name: VIRTUAL_HOST
            value: "os.malcolm.local"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: opensearch-var-local-catrust-volume
          - mountPath: /var/local/curlrc/secretmap
            name: opensearch-opensearch-curlrc-secret-volume
          - mountPath: "/usr/share/opensearch/data"
            name: opensearch-data-volume
          - mountPath: "/opt/opensearch/backup"
            name: opensearch-backup-volume
          - name: opensearch-keystore-default-secret-volume
            mountPath: /usr/share/opensearch/config/bootstrap/secretmap
          - name: opensearch-config-persist-volume
            mountPath: /usr/share/opensearch/config/persist
            subPath: "opensearch"
      initContainers:
      - name: opensearch-dirinit-container
        image: ghcr.io/idaholab/malcolm/dirinit:23.09.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/config:opensearch;/data/opensearch:nodes"
        volumeMounts:
          - name: opensearch-data-volume
            mountPath: "/data/opensearch"
          - name: opensearch-config-persist-volume
            mountPath: "/data/config"
      volumes:
        - name: opensearch-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: opensearch-opensearch-curlrc-secret-volume
          secret:
            secretName: opensearch-curlrc
        - name: opensearch-data-volume
          persistentVolumeClaim:
            claimName: opensearch-claim
        - name: opensearch-backup-volume
          persistentVolumeClaim:
            claimName: opensearch-backup-claim
        - name: opensearch-keystore-default-secret-volume
          secret:
            secretName: opensearch-keystore
        - name: opensearch-config-persist-volume
          persistentVolumeClaim:
            claimName: config-claim