---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: malcolm
spec:
  type: ClusterIP
  ports:
    - port: 22
      protocol: TCP
      name: sftp
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: upload

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
  namespace: malcolm
  labels:
    app: upload
    role: ingest
spec:
  selector:
    matchLabels:
      app: upload
  replicas: 1
  template:
    metadata:
      labels:
        app: upload
        role: ingest
    spec:
      containers:
      - name: upload-container
        image: ghcr.io/idaholab/malcolm/file-upload:25.12.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - name: sftp
            protocol: TCP
            containerPort: 22
          - name: http
            protocol: TCP
            containerPort: 80
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - secretRef:
              name: auth-env
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: upload-var-local-catrust-volume
          - mountPath: "/var/www/upload/server/php/chroot/files"
            name: upload-pcap-volume
            subPath: "upload"
      initContainers:
      - name: upload-dirinit-container
        image: ghcr.io/idaholab/malcolm/dirinit:25.12.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/pcap:upload/tmp/spool,upload/variants"
        volumeMounts:
          - name: upload-pcap-volume
            mountPath: "/data/pcap"
      volumes:
        - name: upload-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: upload-pcap-volume
          persistentVolumeClaim:
            claimName: pcap-claim
