---
apiVersion: v1
kind: Service
metadata:
  name: htadmin
  namespace: malcolm
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: htadmin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htadmin-deployment
  namespace: malcolm
  labels:
    app: htadmin
    role: auth
spec:
  selector:
    matchLabels:
      app: htadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: htadmin
        role: auth
    spec:
      containers:
      - name: htadmin-container
        image: ghcr.io/idaholab/malcolm/htadmin:25.12.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - secretRef:
              name: auth-env
          - configMapRef:
              name: auth-common-env
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: htadmin-var-local-catrust-volume
          - mountPath: /var/www/htadmin/auth
            name: htadmin-config-volume
            subPath: "auth"
          - mountPath: /var/www/htadmin/default/secretmap
            name: htadmin-config-default-secret-volume
          - mountPath: /var/www/htadmin/config
            name: htadmin-config-volume
            subPath: "htadmin"
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
      initContainers:
      - name: htadmin-dirinit-container
        image: ghcr.io/idaholab/malcolm/dirinit:25.12.1
        imagePullPolicy: Always
        stdin: false
        tty: true
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/config:auth,htadmin"
        volumeMounts:
          - name: htadmin-config-volume
            mountPath: "/data/config"
      volumes:
        - name: htadmin-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: htadmin-config-volume
          persistentVolumeClaim:
            claimName: config-claim
        - name: htadmin-config-default-secret-volume
          secret:
            secretName: htadmin-config
        
