---
apiVersion: v1
kind: Service
metadata:
  name: freq
  namespace: malcolm
spec:
  type: ClusterIP
  ports:
    - port: 10004
      protocol: TCP
      name: http
  selector:
    app: freq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freq-deployment
  namespace: malcolm
  labels:
    app: freq
    role: service
spec:
  selector:
    matchLabels:
      app: freq
  replicas: 1
  template:
    metadata:
      labels:
        app: freq
        role: service
    spec:
      containers:
      - name: freq-container
        image: ghcr.io/idaholab/malcolm/freq:25.12.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        ports:
          - name: http
            protocol: TCP
            containerPort: 10004
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: lookup-common-env
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/container_health.sh
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: freq-var-local-catrust-volume
      volumes:
        - name: freq-var-local-catrust-volume
          configMap:
            name: var-local-catrust
