name: strelka-frontend-build-and-push-ghcr

on:
  push:
    branches:
      - main
      - staging
      - pipeline-merge
      - hedgehog-iso-refactor
    paths:
      - 'strelka/**'
      - 'Dockerfiles/strelka-frontend.Dockerfile'
      - 'container-health-scripts/strelka-frontend.sh'
      - 'shared/bin/docker-uid-gid-setup.sh'
      - 'shared/bin/service_check_passthrough.sh'
      - '.trigger_workflow_build'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      service: strelka-frontend
      dockerfile: ./Dockerfiles/strelka-frontend.Dockerfile
