name: suricata-build-and-push-ghcr

on:
  push:
    branches:
      - main
      - staging
      - pipeline-merge
    paths:
      - 'suricata/**'
      - 'Dockerfiles/suricata.Dockerfile'
      - 'container-health-scripts/suricata.sh'
      - 'scripts/malcolm_constants.py'
      - 'scripts/malcolm_utils.py'
      - 'shared/bin/docker-uid-gid-setup.sh'
      - 'shared/bin/netdev-json.sh'
      - 'shared/bin/pcap_processor.py'
      - 'shared/bin/pcap_utils.py'
      - 'shared/bin/service_check_passthrough.sh'
      - 'shared/bin/suricata*'
      - '.trigger_workflow_build'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker-build-push-scan.yml
    with:
      service: suricata
      dockerfile: ./Dockerfiles/suricata.Dockerfile
