on: [workflow_dispatch]

jobs:
  traffic:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "master"

    # Calculates traffic and clones and stores in CSV file
    - name: GitHub traffic
      uses: mmguero-dev/repository-traffic-action@v1
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}

    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Malcolm Workflow
        message: "GitHub traffic"
        add: "./traffic/*"
        ref: "workflow/repository-traffic"  # commits to branch "workflow/repository-traffic"
